
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: nicdev
  password: nicdev

development:
  <<: *default
  database: jumo_assessment_development

test:
  <<: *default
  database: jumo_assessment_test

production:
  <<: *default
  database: jumo_assessment_production
